### PR TITLE
Add obo registry 21

### LINKED ISSUE #18: Context-sensitive help
The PURL system README is intimidating. I'd like to break it down into bite-sized chunks, and display the appropriate chunk below the editor.

Implementation ideas: We can add a "help" key to the JSONSchema. When the cursor moves, we should try to figure out the keyword we're under, lookup that help string, and display it.

### LINKED ISSUE #21: Add OBO Registry to OBO Metadata Editor
This will involved a number of steps, as you see fit @jannahastings.

I want to be merging smallish changes into `master` and deploying them on a regular basis, but I don't want to show registry editing on <https://editor.obolibrary.org> until this is ready. So I think we should use a ["Feature Flag"](https://en.wikipedia.org/wiki/Feature_toggle). We could reuse the `FLASK_ENV` variable: showing the registry stuff for `FLASK_ENV=development` but not for `FLASK_ENV=production`. Or we could use our own flag.

Here are some of the steps that I think will be required:

- implement feature flag
- configure second repository
- configure second set of schemas
- handle new URL paths
- new button on index page: "Edit Registry"
- add fields to new project form
- two step project addition? OR two editors in on page
- select/detect validation profile? foundry, active, orphan, obsolete
- configure second set of autocompletes

### LINKED ISSUE #35: Bug in line number determination for validations of repeating metadata entries
The line number determination seems to fail sometimes, in the validations, when there is more than one entry of the same type. 

Two scenarios that can reproducibly cause problems are: 

1. when there is more than one entry of the same type in a repeat (e.g. in the PURL schema there can be several redirections specified), and the error occurs in the second or subsequent entry, the line number returned is for the first entry

2. when an error has occurred in an entry, is validated and repaired, but then another error is introduced in an entry of the same type but at a different line, the line number returned for the error is for the original error line

### LINKED ISSUE #42: Use ruamel.yaml to improve YAML line determination for JSONSchema errors
One of the most fragile parts of our current code is how we determine the line number of a problem found in the YAML. The JSON Schema validator takes a Python data structure as the input, and `ValidationError` objects contain path information pointing to the problematic part of the data structure, but when we use PyYAML to read the YAML the line numbers are lost. So we've got a system using regular expressions to try and follow the path to the relevant line of the YAML.

[ruamel.yaml](https://pypi.org/project/ruamel.yaml/) is a YAML parsing library designed to support round-trip conversion of YAML files through Python, including formatting and comments. This means that when it loads YAML, the data structure it returns still contains line and column numbers. So given the path to the problem, we can find that part of the data structure and then look up the line and column numbers. Here's an example:

```python
import json
import jsonschema
import sys

from ruamel.yaml import YAML

yaml=YAML()
with open("obi.md") as f:
    data = yaml.load(f)

with open("registry_schema.json") as f:
    registry_schema = json.load(f)

try:
    jsonschema.validate(data, registry_schema)
    print("SUCCESS")
except jsonschema.exceptions.ValidationError as err:
    print(err.message)
    keys = list(err.path)
    if err.validator == "additionalProperties":
        m = err.message
        key = m[m.index("'")+1:m.rindex("'")] # get the added key name; this is hacky
        keys.append(key)
    if len(keys) > 1:
        subset = data
        while len(keys) > 1:
            subset = subset[keys.pop(0)] # follow the path, stopping with one key left
        pos = subset.lc.data[keys[0]] # get ruamel.yaml's line-column information
        print(f"at line {pos[0] + 1}, column {pos[1] + 1}")
    sys.exit(1)
```

I think this approach will be much more robust, and I hope that it won't be to hard to replace our current code.

### PR DESCRIPTION
**Pull request by jannahastings**
Adds schema-based help message and autocomplete as you type in the editor. 

Removes the previously hand-crafted PURL editor autocomplete suggestion code and replaces it with Jinja2-template-generated autocomplete suggestion based on the JSON schema (registry and PURL). Depends on new tags in schema files "suggest: False" for schema entries that should NOT be suggested, and "suggestion": xxx to hand-craft the autocomplete suggestion where the default structure of the schema does not give enough information to build the suggestion automatically.  

Closes #21 

And closes #35 (bug in determining line number for repeated blocks in arrays in yaml) 
And closes #18 (context-sensitive help) 
And closes #42 (use ruamel.yaml to parse yaml and validate against json schema but keeping line numbers)

### CODE REVIEW

**Comment by jamesaoverton** [comment]
This is looking good and working on the test server. Please implement #42, and then I'll do a close review.

**Comment by jamesaoverton** [comment]
It would be nice to be able to read from existing "new ontology" issues that use the current GitHub issue template. Other than that, I think this is ready to go.

**Comment by jamesaoverton** [comment]
@jannahastings Please re-request my review when that last change is made.

**Comment by jannahastings** [comment]
@jamesaoverton This is a first pass at the parsing of the old ontology request issues, as a fall-through if reading from YAML fails. Have a look and see if you think this is a sensible approach -- I worry that all the string handling may be a bit brittle but I couldn't think of a better way to do it?

**Comment by jamesaoverton** [comment]
Yes, that's the approach I would take. The next step up is writing a parser with something like [Lark](https://pypi.org/project/lark/) but I'd rather not.

**Comment by jannahastings** [comment]
@jamesaoverton I've been through and checked everything for both issue templates (old and new), and fixed some bugs I found along the way. I think this is ready for your review now.

**Pull request merged**
